P13/urls.py
from django.contrib import admin
from django.urls import path,include
import yoke
from yoke import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('yoke/',include("yoke.urls")),
]

if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

yoke/urls.py
from django.urls import path
from yoke import views
app_name="yoke"

urlpatterns = [
    path('trail/',views.trial,name="Trial"),
    path('profile/',views.profile,name="profile"),
    path('get_demo/',views.get_demo,name="get_demo"),
    path('post_demo/',views.post_demo,name="post_demo"),
    path('register/',views.register,name="register"),
    path('multi/',views.multi,name="multiselect"),
    path('img/',views.img_upld,name="img"),
    path('img_display/',views.img_display,name="img_disp"),
]

yoke/models.py
from django.db import models

# Create your models here.

yoke/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
# Create your views here.
def trial(request):
    return HttpResponse("<h1>Project is on air</h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"yoke/home.html")

def profile(request):
    name="Yokesh"
    return render(request,"yoke/profile.html",{'name':name})

def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})


def post_demo(request):
    if request.method=="POST":
        name=request.POST.get('name')
        return HttpResponse("<h1>Thanks for submission Mr./Ms. {}</h1>".format(name))
    return render(request,"post_demo.html")

def register(request):
    if request.method=="POST":
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        email=request.POST.get("email")
        password=request.POST.get("pwd")
        phno=request.POST.get("phno")
        date=request.POST.get("birthday_day")
        month=request.POST.get("birthday_month")
        year=request.POST.get("birthday_year")
        gender=request.POST.get("sex")
        if gender=="1":
            gender="FeMale"
        else:
            gender="Male"
        send_mail("Thanks For Registration","hello Mr./Ms.{} {}\n Thanks for Registering".format(first_name,last_name),
        "yokesh2809@gmail.com",[email,],fail_silently=False)
        return HttpResponse("{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>".format(first_name,last_name,email,password,phno,gender,date,month,year))
    return render(request,"yoke/registration.html")

def multi(request):
    if request.method=="POST":
        foods=request.POST.getlist("food")
        languages=request.POST.getlist("language")
        return HttpResponse("<h1>{}{}<h1>".format(foods,languages))
    return render(request,'multiselect.html')

from django.core.files.storage import FileSystemStorage
#uploading and displaying the uploaded image
def img_upld(request):
    return render(request,"img_upld.html")

def img_display(request):
    file_url=False
    if request.method=="POST" and request.FILES:
        image=request.FILES['sam']
        print(image)
        fs=FileSystemStorage()
        file=fs.save(image.name,image)
        file_url=fs.url(file)
                
    return render(request,"img_display.html",context={'file_url':file_url})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE Page</title>
    {% endblock %}
    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-grid.css'%}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-grid.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-reboot.css'%}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-reboot.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <script src="{% static 'js/bootstrap.js'%}"></script>
    <script src="{% static 'js/bootstrap.bundle.js'%}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>

    
</head>
<body>
  {% include "partials/_topbar.html" %}
  {% include "partials/_navbar.html" %}
  
  <img src="{% static 'images/django.png' %}" alt="No Images Found" height="50" width="100">
  
  {% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to base page</h1>
            <img src="{% static 'images/Nature.jpg' %}" alt="No Images Found" height="50" width="100">
        </div>
      </div>
  {% endblock %}
    
  <img src="{% static 'images/Nature.jpg' %}" alt="No Images Found" height="50" width="100">

  {% include "partials/_footer.html" %}

</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>get method</title>
</head>
<body>
    <form method="GET">
        <label form="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="Submit">
    </form>
    <h1>{{name}}</h1>
</body>
</html>

templates/img_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image uplaod</title>
</head>
<body>
    {% if file_url %}
         <img src="{{ file_url }}" alt="no image" height="200" width="250">
    {% endif %}
      
</body>
</html>

templates/img_upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image uplaod</title>
</head>
<body>
    <form action="{% url 'yoke:img_disp' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        Image:<input type="file" name="sam" id="sam">
        <input type="submit" value="Submit">
    </form>
   
      
</body>
</html>

templates/multiselect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MultiSelect and Checkboxes</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="langauges">Choose Your Language:</label>
        <select name="language" id="languages" multiple>
            <option value="Python">Python</option>
            <option value="Java">Java</option>
            <option value="C#">C#</option>
            <option value="C">C Langauge</option>
            <option value="C++">C++</option>
        </select><br>
        <h6>Choose Your Food</h6>
        <label for="idli">
            Idli
        </label>
        <input type="checkbox" name="food" id="idli" value="IDLI">
        <label for="vada">
            vada
        </label>
        <input type="checkbox" name="food" id="vada" value="VADA">
        <label for="dosa">
            Dosa
        </label>
        <input type="checkbox" name="food" id="Dosa" value="DOSA">
        <label for="upma">
            upma
        </label>
        <input type="checkbox" name="food" id="upma" value="UPMA">
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/partials/_footer.html
<div class="alert alert-primary" role="alert">
    <center>Footer</center> 
</div>

templates/partials/_navbar.html
<div class="container">
    <ul class="nav">
        <li class="nav-item">
        <a class="nav-link active" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'yoke:profile' %}">Profile</a>
        </li>
        
    </ul>
</div>

templates/partials/_topbar.html
<div class="alert alert-secondary" role="alert">
    <center>Top Bar</center> 
 </div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Method</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label form="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="Submit">
    </form> 
</body>
</html>

templates/yoke/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Home page</h1>
        </div>
      </div>
{% endblock %}

templates/yoke/profile.html
{% extends "base.html" %}

{% block title %}
    <title>Profile Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}} Profile page</h1>
        </div>
      </div>
{% endblock %}